import streamlit as st

st.set_page_config(page_title="Archmage 0-CD Tester", layout="wide")

st.title("Archmage 0-CD Alternating Tester")
st.markdown("Pure manual inputs. No external API data.")

# --- UI LAYOUT ---
col1, col2 = st.columns(2)

def spell_selection_ui(col, spell_id):
    with col:
        st.subheader(f"Spell {spell_id}")
        
        # Optional text input just to keep the output readable
        spell_name = st.text_input(f"Spell Name (Optional)", value=f"Spell {spell_id}", key=f"name_{spell_id}")
        
        has_charges = st.checkbox(f"Uses Charges / Ammo?", key=f"charges_{spell_id}")
        
        num_charges = 1
        if has_charges:
            st.info("For charge-based spells, enter the Ammo Recharge Time as the Base CD.")
            num_charges = st.number_input(f"Number of Charges", min_value=1, max_value=10, value=1, step=1, key=f"num_charges_{spell_id}")
            
        base_cd = st.number_input(f"Base CD / Recharge Time (s)", min_value=0.0, max_value=200.0, value=10.0, step=0.5, key=f"cd_{spell_id}")
        spec_ah = st.number_input(f"Specific AH", min_value=0.0, max_value=200.0, value=0.0, step=1.0, key=f"ah_{spell_id}")
        
        return spell_name, base_cd, spec_ah, num_charges

s1_name, s1_base_cd, s1_spec_ah, s1_charges = spell_selection_ui(col1, "1")
s2_name, s2_base_cd, s2_spec_ah, s2_charges = spell_selection_ui(col2, "2")

st.divider()

st.subheader("Global Stats")
gen_ah = st.slider("General Ability Haste:", min_value=0.0, max_value=500.0, value=60.0, step=1.0)
purist = st.checkbox("Purist-Caster (10% Total CD Reduction)")

# --- CORE MATH LOGIC ---

# Base refund per single cast
s1_refund_per_cast = s1_base_cd * 0.30
s2_refund_per_cast = s2_base_cd * 0.30

# Total refund if all available charges are expended
s1_total_refund = s1_charges * s1_refund_per_cast
s2_total_refund = s2_charges * s2_refund_per_cast

cd_modifier = 0.90 if purist else 1.0

total_ah_s1 = gen_ah + s1_spec_ah
total_ah_s2 = gen_ah + s2_spec_ah

s1_cd = s1_base_cd * (100 / (100 + total_ah_s1)) * cd_modifier
s2_cd = s2_base_cd * (100 / (100 + total_ah_s2)) * cd_modifier

# Calculate how many charges of a spell are generated by the other spell's total refund
s1_charges_generated = s2_total_refund / s1_cd if s1_cd > 0 else float('inf')
s2_charges_generated = s1_total_refund / s2_cd if s2_cd > 0 else float('inf')

ah_mult = 90 if purist else 100

# Calculate required AH based on the TOTAL refund available from the opposing spell
s1_req_total_ah = (ah_mult * s1_base_cd / s2_total_refund) - 100 if s2_total_refund > 0 else float('inf')
s2_req_total_ah = (ah_mult * s2_base_cd / s1_total_refund) - 100 if s1_total_refund > 0 else float('inf')

s1_req_gen = s1_req_total_ah - s1_spec_ah if s1_req_total_ah != float('inf') else float('inf')
s2_req_gen = s2_req_total_ah - s2_spec_ah if s2_req_total_ah != float('inf') else float('inf')

required_general_ah = max(s1_req_gen, s2_req_gen, 0)

# --- OUTPUT RENDERING ---
st.divider()
st.header("Results")

st.markdown(f"**Archmage refund from {s1_name} → {s2_name}:** `{s1_total_refund:.2f}s` *(from {s1_charges} cast{'s' if s1_charges > 1 else ''})*")
st.markdown(f"**Archmage refund from {s2_name} → {s1_name}:** `{s2_total_refund:.2f}s` *(from {s2_charges} cast{'s' if s2_charges > 1 else ''})*")

st.markdown(f"**{s1_name} In-Game CD / Recharge:** `{s1_cd:.2f}s` *(Using {s1_base_cd}s Base & {total_ah_s1:.0f} Total AH)*")
st.markdown(f"**{s2_name} In-Game CD / Recharge:** `{s2_cd:.2f}s` *(Using {s2_base_cd}s Base & {total_ah_s2:.0f} Total AH)*")

st.divider()
st.subheader("Charge Generation & Loop Test")

st.markdown(f"**Casting {s2_name} ({s2_charges}x)** generates **{s1_charges_generated:.2f}** charges of {s1_name}.")
if s1_cd <= s2_total_refund:
    st.success(f"✅ **{s1_name}: VALID** - {s2_name} completely refunds at least 1 charge of {s1_name}.")
else:
    st.error(f"❌ **{s1_name}: INVALID** - {s1_cd - s2_total_refund:.2f}s remaining for a single charge.")

st.markdown(f"**Casting {s1_name} ({s1_charges}x)** generates **{s2_charges_generated:.2f}** charges of {s2_name}.")
if s2_cd <= s1_total_refund:
    st.success(f"✅ **{s2_name}: VALID** - {s1_name} completely refunds at least 1 charge of {s2_name}.")
else:
    st.error(f"❌ **{s2_name}: INVALID** - {s2_cd - s1_total_refund:.2f}s remaining for a single charge.")

st.divider()
st.subheader("Minimum Ability Haste")

req_s1_str = f"{max(0, s1_req_total_ah):.2f}" if s1_req_total_ah != float('inf') else "Impossible"
req_s2_str = f"{max(0, s2_req_total_ah):.2f}" if s2_req_total_ah != float('inf') else "Impossible"
req_gen_str = f"{required_general_ah:.2f}" if required_general_ah != float('inf') else "Impossible"

st.markdown(f"* Total AH required for {s1_name}: **{req_s1_str}**")
st.markdown(f"* Total AH required for {s2_name}: **{req_s2_str}**")
st.markdown(f"* Target General AH for BOTH: **{req_gen_str}**")

if required_general_ah == float('inf'):
    st.error("RESULT: 0-CD loop is impossible.")
elif gen_ah >= required_general_ah:
    st.success("RESULT: 0-CD alternating loop is mathematically possible! 🎉")
else:
    st.warning(f"RESULT: Not enough AH. Need **{required_general_ah - gen_ah:.2f}** more General AH.")