import streamlit as st
import requests

st.set_page_config(page_title="Archmage 0-CD Tester", layout="wide")

# --- DATA FETCHING (RIOT DATA DRAGON) ---
@st.cache_data(ttl=86400) 
def get_latest_version():
    res = requests.get("https://ddragon.leagueoflegends.com/api/versions.json")
    return res.json()[0] if res.status_code == 200 else "13.24.1"

@st.cache_data(ttl=86400)
def get_champion_list(version):
    res = requests.get(f"https://ddragon.leagueoflegends.com/cdn/{version}/data/en_US/champion.json")
    if res.status_code == 200:
        return list(res.json()['data'].keys())
    return []

@st.cache_data(ttl=86400)
def get_champion_spells(version, champ_name):
    res = requests.get(f"https://ddragon.leagueoflegends.com/cdn/{version}/data/en_US/champion/{champ_name}.json")
    if res.status_code == 200:
        champ_data = res.json()['data'][champ_name]
        # Map Q, W, E, R to the spells
        spells = champ_data['spells']
        spell_mapping = {
            "Q": spells[0],
            "W": spells[1],
            "E": spells[2],
            "R": spells[3]
        }
        return spell_mapping
    return {}

version = get_latest_version()
champions = get_champion_list(version)

st.title("Archmage 0-CD Alternating Tester")
st.markdown(f"*Using live data from LoL Patch {version}*")

# --- GLOBAL CHAMPION SELECTION ---
st.subheader("Champion Selection")
selected_champ = st.selectbox("Select Champion", options=champions)
champ_spells = get_champion_spells(version, selected_champ)

st.divider()

# --- UI LAYOUT ---
col1, col2 = st.columns(2)

def spell_selection_ui(col, spell_id, spells):
    with col:
        st.subheader(f"Spell {spell_id}")
        
        if spells:
            spell_key = st.selectbox(f"Select Skill {spell_id}", options=["Q", "W", "E", "R"], key=f"skill_key_{spell_id}")
            selected_spell = spells[spell_key]
            st.markdown(f"**{selected_spell['name']}**")
            
            # Allow user to select the rank of the spell to get the correct base CD
            rank_index = st.slider(f"Skill Rank", min_value=1, max_value=len(selected_spell['cooldown']), value=1, key=f"rank_{spell_id}") - 1
            fetched_cd = selected_spell['cooldown'][rank_index]
        else:
            fetched_cd = 10.0
            st.error("Failed to load champion data.")

        # Allow manual override for Edge Cases
        st.markdown("---")
        has_charges = st.checkbox(f"Uses Charges / Ammo?", key=f"charges_{spell_id}")
        
        num_charges = 1
        if has_charges:
            st.info("For charge-based spells, Archmage uses the Ammo Recharge Time as the Base CD.")
            num_charges = st.number_input(f"Number of Charges", min_value=1, max_value=10, value=1, step=1, key=f"num_charges_{spell_id}")
            
        base_cd = st.number_input(f"Base CD / Recharge Time (s)", min_value=0.0, max_value=200.0, value=float(fetched_cd), step=0.5, key=f"cd_{spell_id}")
        spec_ah = st.number_input(f"Specific AH", min_value=0.0, max_value=200.0, value=0.0, step=1.0, key=f"ah_{spell_id}")
        
        return base_cd, spec_ah, num_charges

# Pass the globally fetched spells down into the column UI
s1_base_cd, s1_spec_ah, s1_charges = spell_selection_ui(col1, "1", champ_spells)
s2_base_cd, s2_spec_ah, s2_charges = spell_selection_ui(col2, "2", champ_spells)

st.divider()

st.subheader("Global Stats")
gen_ah = st.slider("General Ability Haste:", min_value=0.0, max_value=500.0, value=60.0, step=1.0)
purist = st.checkbox("Purist-Caster (10% Total CD Reduction)")

# --- CORE MATH LOGIC ---

# Base refund per single cast
s1_refund_per_cast = s1_base_cd * 0.30
s2_refund_per_cast = s2_base_cd * 0.30

# Total refund if all available charges are expended
s1_total_refund = s1_charges * s1_refund_per_cast
s2_total_refund = s2_charges * s2_refund_per_cast

cd_modifier = 0.90 if purist else 1.0

total_ah_s1 = gen_ah + s1_spec_ah
total_ah_s2 = gen_ah + s2_spec_ah

s1_cd = s1_base_cd * (100 / (100 + total_ah_s1)) * cd_modifier
s2_cd = s2_base_cd * (100 / (100 + total_ah_s2)) * cd_modifier

# Calculate how many charges of a spell are generated by the other spell's total refund
s1_charges_generated = s2_total_refund / s1_cd if s1_cd > 0 else float('inf')
s2_charges_generated = s1_total_refund / s2_cd if s2_cd > 0 else float('inf')

ah_mult = 90 if purist else 100

# Calculate required AH based on the TOTAL refund available from the opposing spell
s1_req_total_ah = (ah_mult * s1_base_cd / s2_total_refund) - 100 if s2_total_refund > 0 else float('inf')
s2_req_total_ah = (ah_mult * s2_base_cd / s1_total_refund) - 100 if s1_total_refund > 0 else float('inf')

s1_req_gen = s1_req_total_ah - s1_spec_ah if s1_req_total_ah != float('inf') else float('inf')
s2_req_gen = s2_req_total_ah - s2_spec_ah if s2_req_total_ah != float('inf') else float('inf')

required_general_ah = max(s1_req_gen, s2_req_gen, 0)

# --- OUTPUT RENDERING ---
st.divider()
st.header("Results")

st.markdown(f"**Archmage refund from S1 → S2:** `{s1_total_refund:.2f}s` *(from {s1_charges} cast{'s' if s1_charges > 1 else ''})*")
st.markdown(f"**Archmage refund from S2 → S1:** `{s2_total_refund:.2f}s` *(from {s2_charges} cast{'s' if s2_charges > 1 else ''})*")

st.markdown(f"**S1 In-Game CD / Recharge:** `{s1_cd:.2f}s` *(Using {s1_base_cd}s Base & {total_ah_s1:.0f} Total AH)*")
st.markdown(f"**S2 In-Game CD / Recharge:** `{s2_cd:.2f}s` *(Using {s2_base_cd}s Base & {total_ah_s2:.0f} Total AH)*")

st.divider()
st.subheader("Charge Generation & Loop Test")

st.markdown(f"**Casting S2 ({s2_charges}x)** generates **{s1_charges_generated:.2f}** charges of S1.")
if s1_cd <= s2_total_refund:
    st.success(f"✅ **Spell 1: VALID** - S2 completely refunds at least 1 charge of S1.")
else:
    st.error(f"❌ **Spell 1: INVALID** - {s1_cd - s2_total_refund:.2f}s remaining for a single charge.")

st.markdown(f"**Casting S1 ({s1_charges}x)** generates **{s2_charges_generated:.2f}** charges of S2.")
if s2_cd <= s1_total_refund:
    st.success(f"✅ **Spell 2: VALID** - S1 completely refunds at least 1 charge of S2.")
else:
    st.error(f"❌ **Spell 2: INVALID** - {s2_cd - s1_total_refund:.2f}s remaining for a single charge.")

st.divider()
st.subheader("Minimum Ability Haste")

req_s1_str = f"{max(0, s1_req_total_ah):.2f}" if s1_req_total_ah != float('inf') else "Impossible"
req_s2_str = f"{max(0, s2_req_total_ah):.2f}" if s2_req_total_ah != float('inf') else "Impossible"
req_gen_str = f"{required_general_ah:.2f}" if required_general_ah != float('inf') else "Impossible"

st.markdown(f"* Total AH required for S1: **{req_s1_str}**")
st.markdown(f"* Total AH required for S2: **{req_s2_str}**")
st.markdown(f"* Target General AH for BOTH: **{req_gen_str}**")

if required_general_ah == float('inf'):
    st.error("RESULT: 0-CD loop is impossible.")
elif gen_ah >= required_general_ah:
    st.success("RESULT: 0-CD alternating loop is mathematically possible! 🎉")
else:
    st.warning(f"RESULT: Not enough AH. Need **{required_general_ah - gen_ah:.2f}** more General AH.")